import com.electronwill.nightconfig.core.file.FileConfig

import java.nio.file.Files
import java.nio.file.StandardCopyOption
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.electronwill.night-config:toml:3.9.0'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'java'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.+'
}

version = mod_version
group = mod_group_id

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
sourceSets.main.resources { srcDir 'src/generated/resources' }

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    mods {
        "${mod_id}" {
            //noinspection GroovyAssignabilityCheck
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
        }

        server {
            server()
        }

        data {
            data()
        }
    }
}

repositories {
    mavenCentral()
    flatDir {dir 'libs'}
    flatDir {dir 'pack/mods'}

    maven { url 'https://maven.fallenbreath.me/releases' }

    maven {
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }

    maven {
        url = 'https://curse.cleanroommc.com'
        content { includeGroup 'curse.maven' }
    }

    maven {
        url = "https://maven.su5ed.dev/releases/"
    }

    maven {
        url "https://cursemaven.com"
    }

    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    annotationProcessor("org.sinytra:sponge-mixin:${mixin_version}")
    compileOnly("org.sinytra:sponge-mixin:${mixin_version}")
    //clientAdditionalRuntimeClasspath project(':mixin-bootstrap') // Do not remove me!
    implementation(jarJar "me.fallenbreath:conditional-mixin-forge:${mixin_conditional}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}"))

    compileOnly "dev.su5ed.sinytra.fabric-api:fabric-api:${fabric_api_version}"
    modCompileOnly("curse.maven:epic-mob-siege-nightmare-957414:5003615")
    modCompileOnly "net.jmb19905:carbonize:1.0.0+1.20.1"
    modCompileOnly(pack.curseforge.cb.multipart)
    modCompileOnly(pack.curseforge.no.tree.punching)
    modCompileOnly(pack.curseforge.tough.as.nails)
    modCompileOnly "buildcraft:buildcraft:7.99.24.9-1.20.1-2025-04-26-all"
    modCompileOnly(pack.curseforge.cofh.core)
    modCompileOnly(pack.curseforge.actually.subtractions)
    modCompileOnly(pack.curseforge.decorative.blocks)
    modCompileOnly("cofh.thermal.foundation:thermal_core:1.20.1-11.0.6.24")

    def modCategories = (Map<String, List<String>>) new JsonSlurper().parse(file("src/main/resources/META-INF/mod_categories.json"))

    validateModCategories(modCategories)
    modCategories = applySubCategories(modCategories)

    if (providers.gradleProperty("dump_parsed_json").getOrElse("false").toBoolean())
        println JsonOutput.prettyPrint(JsonOutput.toJson(modCategories))

    // Libraries
        // Fabric
        if (isModEnabled(modCategories, "fabric_api"))
            modRuntimeOnly(pack.curseforge.forgified.fabric.api)
        // Forge
        if (isModEnabled(modCategories, "architectury"))
            modRuntimeOnly(pack.curseforge.architectury.api)
        if (isModEnabled(modCategories, "cb_multipart"))
            modRuntimeOnly(pack.curseforge.cb.multipart)
        if (isModEnabled(modCategories, "codechickenlib"))
            modRuntimeOnly(pack.curseforge.codechicken.lib.'1'.'8')
        if (isModEnabled(modCategories, "kubejs"))
            modRuntimeOnly(pack.curseforge.kubejs)
        if (isModEnabled(modCategories, "rhino"))
            modRuntimeOnly(pack.curseforge.rhino)
        if (isModEnabled(modCategories, "connectormod")) {
            runtimeOnly("org.sinytra.connector:Connector-1.0.0-beta.50+1.20.1")
            //modRuntimeOnly(pack.curseforge.sinytra.connector)
            //clientAdditionalRuntimeClasspath project(':mixin-bootstrap') // Do not remove me!
        }
        if (isModEnabled(modCategories, "owo"))
            modRuntimeOnly(pack.curseforge.owo.lib)
        if (isModEnabled(modCategories, "cloth_config"))
            modRuntimeOnly(pack.curseforge.cloth.config)
        if (isModEnabled(modCategories, "glitchcore"))
            modRuntimeOnly(pack.curseforge.glitchcore)
        if (isModEnabled(modCategories, "cofh_core"))
            modRuntimeOnly(pack.curseforge.cofh.core)
    // Lifecycle
    if (isModEnabled(modCategories, "epicsiegemod"))
        modRuntimeOnly(pack.curseforge.epic.siege.mod)
    // Building
    if (isModEnabled(modCategories, "decorative_blocks"))
        modRuntimeOnly(pack.curseforge.decorative.blocks)
    // Technology
    if (isModEnabled(modCategories, "carbonize"))
        modRuntimeOnly("net.jmb19905:carbonize:1.0.0+1.20.1")
    if (isModEnabled(modCategories, "actuallyadditions"))
        modRuntimeOnly(pack.curseforge.actually.subtractions)
    if (isModEnabled(modCategories, "buildcraftcore"))
        modRuntimeOnly "buildcraft:buildcraft:7.99.24.9-1.20.1-2025-04-26-all"
        // Primitive Technology 1
        if (isModEnabled(modCategories, "toughasnails"))
            modRuntimeOnly(pack.curseforge.tough.as.nails)
        if (isModEnabled(modCategories, "notreepunching"))
            modRuntimeOnly(pack.curseforge.no.tree.punching)
        if (isModEnabled(modCategories, "treechop"))
            modRuntimeOnly(pack.curseforge.treechop)
        if (isModEnabled(modCategories, "primalstage"))
            modRuntimeOnly(pack.curseforge.primal.stage)
        if (isModEnabled(modCategories, "hardcore_torches"))
            modRuntimeOnly(pack.curseforge.hardcore.torches.forge)
        // Electrical 2
        if (isModEnabled(modCategories, "thermal_foundation"))
            modRuntimeOnly(pack.curseforge.thermal.foundation)

    // World
    if (isModEnabled(modCategories, "aether"))
        modRuntimeOnly(pack.curseforge.aether)
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
    config "mixins.${mod_id}.json"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version: forge_version,
            forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

jar {
    manifest.attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : mod_authors,
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : mod_authors,
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            'MixinConfigs'            : "mixins.${mod_id}.json",
    ])
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.register('backupPack') {
    if (providers.gradleProperty("backupPack").getOrElse("false").toBoolean()) {
        doLast {
            def timestamp = new Date().format('yyyyMMdd-HHmmss')
            def backupDir = file("${layout.buildDirectory.get()}/pack-backups/$timestamp")

            copy {
                from('pack')
                into(backupDir)
            }

            println("Backed up /pack/ to ${backupDir}")
        }
    } else doLast {
        println("Skipped '/pack/' backup.")
    }
}

tasks.register('backupRun') {
    if (providers.gradleProperty("backupRun").getOrElse("false").toBoolean()) {
        doLast {
            def timestamp = new Date().format('yyyyMMdd-HHmmss')
            def backupDir = file("${layout.buildDirectory.get()}/run-backups/$timestamp")

            copy {
                from('run')
                into(backupDir)
            }

            println("Backed up /pack/ to ${backupDir}")
        }
    } else doLast {
        println("Skipped '/run/' backup.")
    }
}

tasks.register('processStaticAssets', Copy) {
    dependsOn('backupPack')
    dependsOn('backupRun')
    into('run')

    staticAssetFolders.split(',').each { dir ->
        dir = dir.trim()
        from("pack/${dir}") {
            into(dir)
        }
    }
}

['runClient', 'runServer', 'runData'].each { name ->
    tasks.named(name) {
        dependsOn('processStaticAssets')
    }
}

tasks.register('processDynamicAssets') {
    dependsOn('backupPack')
    dependsOn('backupRun')

    doLast {
        dynamicAssetFolders.split(',').each { dir ->
            dir = dir.trim()
            sync {
                it.from("run/${dir}")
                it.into("pack/${dir}")
            }
        }
    }
}

tasks.register('updatePackToml') {
    def packFile = file(layout.projectDirectory.dir("pack/pack.toml"))
    def packToml = FileConfig.of(packFile)
    packToml.load()
    packToml.set('version', modpack_version)
    packToml.set('name', mod_name)
    packToml.save()
    println("Updated pack.toml with current values")
}

tasks.register('refreshPackwiz', Exec) {
    dependsOn('updatePackToml')
    workingDir layout.projectDirectory.dir("pack")
    commandLine 'packwiz', 'refresh'

    doLast {
        def packFile = file(layout.projectDirectory.dir("pack/pack.toml"))
        def packToml = FileConfig.of(packFile)
        packToml.load()
        packToml.set('version', modpack_version)
        packToml.set('name', mod_name)
        packToml.save()
        println("Updated pack.toml with current values")
    }
}

tasks.register('compilePackwiz') {
    dependsOn('backupPack', 'backupRun', 'refreshPackwiz', 'build')

    doLast {
        sync {
            it.from layout.projectDirectory.dir("pack")
            it.into layout.buildDirectory.dir("packwiz/compiled")
        }
        println('Added packwiz files...')
        dynamicAssetFolders.split(',').each { dir ->
            dir = dir.trim()
            copy {
                it.from"run/${dir}"
                it.into layout.buildDirectory.dir("packwiz/compiled/${dir}")
            }
        }
        println('Added dynamic asset folders...')
        def modJar = layout.buildDirectory
                .file("libs/${mod_id}-${mod_version}.jar")
                .get()
                .asFile
        def modCompilationDir = layout.buildDirectory.dir("packwiz/compiled/mods").get().asFile
        modCompilationDir.mkdirs()
        Files.copy(
                modJar.toPath(),
                modCompilationDir.toPath().resolve(modJar.name),
                StandardCopyOption.REPLACE_EXISTING
        )
        println('Added mod jar...')
    }
}

tasks.register('packwizCurseforgeExport', Exec) {
    dependsOn('compilePackwiz')
    workingDir layout.buildDirectory.dir("packwiz/compiled")
    commandLine 'packwiz', 'curseforge', 'export'
}

tasks.register('migratePackwizBuildArtifact') {
    dependsOn('packwizCurseforgeExport')
    doLast {
        def buildArtifact = file(layout.buildDirectory.file("packwiz/compiled/${mod_name}-${modpack_version}.zip"))
        def buildDir = layout.buildDirectory.dir("packwiz/artifacts").get().asFile
        buildDir.mkdirs()
        Files.move(
                buildArtifact.toPath(),
                buildDir.toPath().resolve(buildArtifact.name),
                StandardCopyOption.REPLACE_EXISTING
        )
        println("Migrated ${mod_name}-${modpack_version}.zip to artifacts..")
    }
}

tasks.register('packwizExport') {
    dependsOn('migratePackwizBuildArtifact')
}

void validateModCategories(Map<String, List<String>> modCategories) {
    // Check to see if mod category is in correct format
    modCategories.entrySet().stream().forEach {entry ->
        var keylist = entry.key.split(':')
        if (    entry.key != entry.key.toLowerCase() ||
                entry.key.contains(" ") ||
                keylist.length != 2 ||
                !(keylist[0] == "[optional]" || keylist[0] == "[required]")
        )
            throw new RuntimeException("Mod category '${entry.key}' is does not obey naming convention!")
        if (!providers.gradleProperty("enable_${getCategoryName entry.key}").present)
            println("Category '${entry.key}' has no gradle properties definition. This will be assumed to be false.")
    }
}

Map<String, Set<String>> applySubCategories(Map<String, List<String>> modCategories) {
    Map<String, Set<String>> newModCategories = new HashMap<>()
    modCategories.forEach {category, entries ->
        newModCategories.put(category, applySubCategory(modCategories, category, new ArrayList<String>()))}
    return newModCategories
}

Set<String> applySubCategory(Map<String, List<String>> modCategories, String workingCategory, List<String> iteratedCategories) {
    // Check if there are cyclic dependencies on mod categories
    if (iteratedCategories.stream().anyMatch {category -> (category == workingCategory) })
        throw new RuntimeException("[ERROR]: Cyclic category dependencies:  ${iteratedCategories}!")
    // Check that the working category actually exists
    if (modCategories.containsKey("[optional]:" + workingCategory))
        workingCategory = "[optional]:" + workingCategory
    else if (modCategories.containsKey("[required]:" + workingCategory))
        workingCategory = "[required]:" + workingCategory
    else if (!(workingCategory.contains("[optional]:") && modCategories.containsKey(workingCategory)) &&
            !(workingCategory.contains("[required]:") && modCategories.containsKey(workingCategory)))
        throw new RuntimeException("[ERROR]: Category \"${workingCategory}\" does not exist in ${modCategories}!")
    // Add working category
    iteratedCategories.add(workingCategory)
    // Iterate for entries
    Set<String> filledEntries = new HashSet<>()
    modCategories.get(workingCategory).forEach {entry ->
        // If entry is non-existent, remove
        if (entry == null || entry.isEmpty())
            return
        // Add normally if it's a regular modid entry
        if (!entry.contains("#"))
            filledEntries.add(entry)
        // Apply subcategories for entry
        else filledEntries.addAll(applySubCategory(modCategories, entry.replace("#", ""), iteratedCategories))
    }
    // Remove working category: Avoids sibling branches duplicating entries in iterated categories
    iteratedCategories.remove(workingCategory)
    return filledEntries
}

static String getCategoryName(String rawCategoryName) {
    return rawCategoryName.trim().split(":")[1]
}

// Do not make this static
// Function: Has no unfulfilled requirements & atleast one option
boolean isModEnabled(Map<String, Set<String>> modCategories, String modid) {
    //Check required categories
    boolean allRequirementsSatisfied = modCategories.entrySet().stream()
            // Get requirements
            .filter{entry -> entry.key.contains("[required]")}
            // Remove categories that are not a requirement of mod
            .filter {entry -> entry.value.stream().anyMatch {categoryModId -> (modid == categoryModId) }}
            // Test all categories to see if they are all enabled
            .allMatch { entry -> providers.gradleProperty("enable_${getCategoryName entry.key}").getOrElse("false").toBoolean()}
    if (!allRequirementsSatisfied)
        return false
    //Check optional categories
    return modCategories.entrySet().stream()
            // Get options
            .filter{entry -> entry.key.contains("[optional]")}
            // Remove options that are disabled
            .filter { entry ->
                providers.gradleProperty("enable_${getCategoryName entry.key}").getOrElse("false").toBoolean()}
            // Combine all enabled options' modids
            .flatMap{entry -> entry.value.stream()}
            // Test all categories to see if any are enabled
            .anyMatch{modElement -> (modid == modElement) }
}