//file:noinspection DependencyNotationArgument
//file:noinspection GroovyImplicitNullArgumentCall
//file:noinspection SpellCheckingInspection

import com.stockieslad.mobsiege.mod_category.ModChecker

plugins {
    id 'eclipse'
    id 'idea'
    id 'java'
    id 'groovy'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.+'
    id "modpack"
}

version = mod_version
group = mod_group_id

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
        groovy {
            //noinspection GroovyAssignabilityCheck
            srcDir "$rootDir/buildSrc/src/main/groovy/com/stockieslad/$mod_id"
        }
    }
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    mods {
        "${mod_id}" {
            //noinspection GrUnresolvedAccess, GroovyAssignabilityCheck
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
        }

        server {
            server()
        }

        data {
            data()
        }
    }
}

repositories {
    mavenCentral()
    flatDir {dir 'libs'}
    flatDir {dir 'pack/mods'}

    maven { url 'https://maven.fallenbreath.me/releases' }

    maven {
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }

    maven {
        url = 'https://curse.cleanroommc.com'
        content { includeGroup 'curse.maven' }
    }

    maven {
        url = "https://maven.su5ed.dev/releases/"
    }

    maven {
        url "https://cursemaven.com"
    }

    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    annotationProcessor("org.sinytra:sponge-mixin:${mixin_version}")
    compileOnly("org.sinytra:sponge-mixin:${mixin_version}")
    //clientAdditionalRuntimeClasspath project(':mixin-bootstrap') // Do not remove me!
    implementation(jarJar "me.fallenbreath:conditional-mixin-forge:${mixin_conditional}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}"))
    implementation("org.apache.groovy:groovy:${groovy_version}")
    implementation("org.apache.groovy:groovy-json:${groovy_version}")

    compileOnly "dev.su5ed.sinytra.fabric-api:fabric-api:${fabric_api_version}"
    modCompileOnly("curse.maven:epic-mob-siege-nightmare-957414:5003615")
    modCompileOnly "net.jmb19905:carbonize:1.0.0+1.20.1"
    modCompileOnly(pack.curseforge.cb.multipart)
    modCompileOnly(pack.curseforge.no.tree.punching)
    modCompileOnly(pack.curseforge.tough.as.nails)
    modCompileOnly "buildcraft:buildcraft:7.99.24.9-1.20.1-2025-04-26-all"
    modCompileOnly(pack.curseforge.cofh.core)
    modCompileOnly(pack.curseforge.actually.subtractions)
    modCompileOnly(pack.curseforge.decorative.blocks)
    modCompileOnly("cofh.thermal.foundation:thermal_core:1.20.1-11.0.6.24")

    //def modCategories = (Map<String, List<String>>) new JsonSlurper().parse(file("src/main/resources/META-INF/mod_categories.json"))
    //modCategories = new HashMap<String, List<String>>(modCategories)

    //validateModCategories(modCategories)
    //modCategories = applySubCategories(modCategories)

    var mods = modpack.modCategoryProvider().getModChecker() as ModChecker

    // Libraries
        // Fabric
        if (mods.isModEnabled("fabric_api"))
            modRuntimeOnly(pack.curseforge.forgified.fabric.api)
        // Forge
        if (mods.isModEnabled("architectury"))
            modRuntimeOnly(pack.curseforge.architectury.api)
        if (mods.isModEnabled("cb_multipart"))
            modRuntimeOnly(pack.curseforge.cb.multipart)
        if (mods.isModEnabled("codechickenlib"))
            modRuntimeOnly(pack.curseforge.codechicken.lib.'1'.'8')
        if (mods.isModEnabled("rhino"))
            modRuntimeOnly(pack.curseforge.rhino)
        if (mods.isModEnabled("connectormod")) {
            modRuntimeOnly("org.sinytra.connector:Connector-1.0.0-beta.50+1.20.1")
            //modRuntimeOnly(pack.curseforge.sinytra.connector)
            //clientAdditionalRuntimeClasspath project(':mixin-bootstrap') // Do not remove me!
        }
        if (mods.isModEnabled("owo"))
            modRuntimeOnly(pack.curseforge.owo.lib)
        if (mods.isModEnabled("cloth-config"))
            modRuntimeOnly(pack.curseforge.cloth.config)
        if (mods.isModEnabled("glitchcore"))
            modRuntimeOnly(pack.curseforge.glitchcore)
        if (mods.isModEnabled("cofh_core"))
            modRuntimeOnly(pack.curseforge.cofh.core)
        if (mods.isModEnabled("geckolib"))
            modRuntimeOnly(pack.curseforge.geckolib)
        if (mods.isModEnabled("gml"))
            modRuntimeOnly(pack.curseforge.gml)
    //Tweaks
    if (mods.isModEnabled("incontrol"))
        modRuntimeOnly(pack.curseforge."in".control)
    if (mods.isModEnabled("kubejs"))
        modRuntimeOnly(pack.curseforge.kubejs)
    if (mods.isModEnabled("lootjs"))
        modRuntimeOnly(pack.curseforge.lootjs)
    if (mods.isModEnabled("entityjs"))
        modRuntimeOnly(pack.curseforge.entityjs)
    if (mods.isModEnabled("probejs"))
        modRuntimeOnly(pack.curseforge.probejs)
    if (mods.isModEnabled("kubejsadditions"))
        modRuntimeOnly(pack.curseforge.kubejs.additions)
    if (mods.isModEnabled("kubejsoffline"))
        modRuntimeOnly(pack.curseforge.kubejs.offline)

    // Lifecycle
    if (mods.isModEnabled("epicsiegemod"))
        modRuntimeOnly(pack.curseforge.epic.siege.mod)
    // Building
    if (mods.isModEnabled("decorative_blocks"))
        modRuntimeOnly(pack.curseforge.decorative.blocks)
    // Technology
    if (mods.isModEnabled("carbonize"))
        modRuntimeOnly("net.jmb19905:carbonize:1.0.0+1.20.1")
    if (mods.isModEnabled("actuallyadditions"))
        modRuntimeOnly(pack.curseforge.actually.subtractions)
    if (mods.isModEnabled("buildcraftcore"))
        modRuntimeOnly "buildcraft:buildcraft:7.99.24.9-1.20.1-2025-04-26-all"
        // Primitive Technology 1
        if (mods.isModEnabled("toughasnails"))
            modRuntimeOnly(pack.curseforge.tough.as.nails)
        if (mods.isModEnabled("notreepunching"))
            modRuntimeOnly(pack.curseforge.no.tree.punching)
        if (mods.isModEnabled("treechop"))
            modRuntimeOnly(pack.curseforge.treechop)
        if (mods.isModEnabled("primalstage"))
            modRuntimeOnly(pack.curseforge.primal.stage)
        if (mods.isModEnabled("hardcore_torches"))
            modRuntimeOnly(pack.curseforge.hardcore.torches.forge)
        // Electrical 2
        if (mods.isModEnabled("thermal_foundation"))
            modRuntimeOnly(pack.curseforge.thermal.foundation)

    // World
    if (mods.isModEnabled("aether"))
        modRuntimeOnly(pack.curseforge.aether)

    configurations.configureEach {
        exclude(group: "net.minecraftforge", module: "srgutils")
    }

    // Check missing dependencies
    mods.printMissingDependencies()
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
    config "mixins.${mod_id}.json"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version: forge_version,
            forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

jar {
    manifest.attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : mod_authors,
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : mod_authors,
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            'MixinConfigs'            : "mixins.${mod_id}.json",
    ])
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.named('compileGroovy') {
    classpath = sourceSets.main.compileClasspath
}

tasks.named('compileJava') {
    classpath += files(sourceSets.main.groovy.classesDirectory)
}

apply from: "$rootDir/gradle_scripts/packwiz.gradle"
apply from: "$rootDir/gradle_scripts/category_settings.gradle"
/*

tasks.register('backupPack') {
    if (providers.gradleProperty("backupPack").getOrElse("false").toBoolean()) {
        doLast {
            def timestamp = new Date().format('yyyyMMdd-HHmmss')
            def backupDir = file("${layout.buildDirectory.get()}/pack-backups/$timestamp")

            copy {
                from('pack')
                into(backupDir)
            }

            println("Backed up /pack/ to ${backupDir}")
        }
    } else doLast {
        println("Skipped '/pack/' backup.")
    }
}

tasks.register('backupRun') {
    if (providers.gradleProperty("backupRun").getOrElse("false").toBoolean()) {
        doLast {
            def timestamp = new Date().format('yyyyMMdd-HHmmss')
            def backupDir = file("${layout.buildDirectory.get()}/run-backups/$timestamp")

            copy {
                from('run')
                into(backupDir)
            }

            println("Backed up /pack/ to ${backupDir}")
        }
    } else doLast {
        println("Skipped '/run/' backup.")
    }
}

tasks.register('processStaticAssets', Copy) {
    dependsOn('backupPack')
    dependsOn('backupRun')
    into('run')

    staticAssetFolders.split(',').each { dir ->
        dir = dir.trim()
        from("pack/${dir}") {
            into(dir)
        }
    }
}

['runClient', 'runServer', 'runData'].each { name ->
    tasks.named(name) {
        dependsOn('processStaticAssets')
    }
}

tasks.register('processDynamicAssets') {
    dependsOn('backupPack')
    dependsOn('backupRun')

    doLast {
        dynamicAssetFolders.split(',').each { dir ->
            dir = dir.trim()
            sync {
                it.from("run/${dir}")
                it.into("pack/${dir}")
            }
        }
    }
}

tasks.register('updatePackToml') {
    def packFile = file(layout.projectDirectory.dir("pack/pack.toml"))
    def packToml = FileConfig.of(packFile)
    packToml.load()
    packToml.set('version', modpack_version)
    packToml.set('name', mod_name)
    packToml.save()
    println("Updated pack.toml with current values")
}

tasks.register('refreshPackwiz', Exec) {
    dependsOn('updatePackToml')
    workingDir layout.projectDirectory.dir("pack")
    commandLine 'packwiz', 'refresh'

    doLast {
        def packFile = file(layout.projectDirectory.dir("pack/pack.toml"))
        def packToml = FileConfig.of(packFile)
        packToml.load()
        packToml.set('version', modpack_version)
        packToml.set('name', mod_name)
        packToml.save()
        println("Updated pack.toml with current values")
    }
}

tasks.register('compilePackwiz') {
    dependsOn('backupPack', 'backupRun', 'refreshPackwiz', 'build')

    doLast {
        sync {
            it.from layout.projectDirectory.dir("pack")
            it.into layout.buildDirectory.dir("packwiz/compiled")
        }
        println('Added packwiz files...')
        dynamicAssetFolders.split(',').each { dir ->
            dir = dir.trim()
            copy {
                it.from"run/${dir}"
                it.into layout.buildDirectory.dir("packwiz/compiled/${dir}")
            }
        }
        println('Added dynamic asset folders...')
        def modJar = layout.buildDirectory
                .file("libs/${mod_id}-${mod_version}.jar")
                .get()
                .asFile
        def modCompilationDir = layout.buildDirectory.dir("packwiz/compiled/mods").get().asFile
        modCompilationDir.mkdirs()
        Files.copy(
                modJar.toPath(),
                modCompilationDir.toPath().resolve(modJar.name),
                StandardCopyOption.REPLACE_EXISTING
        )
        println('Added mod jar...')
    }
}

tasks.register('packwizCurseforgeExport', Exec) {
    dependsOn('compilePackwiz')
    workingDir layout.buildDirectory.dir("packwiz/compiled")
    commandLine 'packwiz', 'curseforge', 'export'
}

tasks.register('migratePackwizBuildArtifact') {
    dependsOn('packwizCurseforgeExport')
    doLast {
        def buildArtifact = file(layout.buildDirectory.file("packwiz/compiled/${mod_name}-${modpack_version}.zip"))
        def buildDir = layout.buildDirectory.dir("packwiz/artifacts").get().asFile
        buildDir.mkdirs()
        Files.move(
                buildArtifact.toPath(),
                buildDir.toPath().resolve(buildArtifact.name),
                StandardCopyOption.REPLACE_EXISTING
        )
        println("Migrated ${mod_name}-${modpack_version}.zip to artifacts..")
    }
}

tasks.register('packwizExport') {
    dependsOn('migratePackwizBuildArtifact')
}
*/
/*
tasks.register("generateModCategorySettings") {
    def outputDir = layout.buildDirectory.dir("resources/main/META-INF")
    doLast {
        def dir = outputDir.get().asFile
        dir.mkdirs()

        def modCategories = (Map<String, List<String>>) new JsonSlurper().parse(file("src/main/resources/META-INF/mod_categories.json"))
        def modProperties = [:]
        modCategories.entrySet().stream().forEach {entry ->
            modProperties[entry.key] = providers.gradleProperty("enable_${getCategoryName entry.key}").getOrElse("false").toBoolean()
        }

        new File(dir, "mod_category_settings.json").text = JsonOutput.prettyPrint(JsonOutput.toJson(modProperties))
    }
}

tasks.named("processResources") {
    dependsOn("generateModCategorySettings")
} */



/**
 * <p> Category format:  [optional/required/constraint]:modid
 * <p> Optionals - At least one option must be enabled for a given mod.
 * <p> Requirements - All requirements must be enabled for a given mod
 * <p> Constraint - Enables the dependents of a given mod
 * @param modCategories The json object for mod_categories.json
 */
/*
void validateModCategories(Map<String, List<String>> modCategories) {
    List<String> scannedCategories = new ArrayList<>()
    // Iterate through all categories
    modCategories.entrySet().stream().forEach {entry ->
        // Error if duplicate
        if (scannedCategories.contains(getCategoryName(entry.key)))
            throw new RuntimeException("There are two mod categories with the same name: '${getCategoryName entry.key}'")
        // Warn if empty category
        if (entry.value.size() == 0)
            println("[WARN]: Mod category '${getCategoryName(entry.key)}' is empty.")
        // Scan for correct category format
        var keylist = entry.key.split(':')
        if (    entry.key != entry.key.toLowerCase() ||
                entry.key.contains(" ") ||
                keylist.length != 2 ||
                !(      keylist[0] == "[optional]" ||
                        keylist[0] == "[required]" ||
                        keylist[0] == "[constraint]"
                )
        ) throw new RuntimeException("Mod category '${entry.key}' is does not obey naming convention!")
        // Check for cyclic constraints
        entry.value.stream().forEach { dependencyModid -> {
            List<String> parents = new ArrayList<>();
            if (entry.key.contains("[constraint]"))
                parents.add(entry.key.split(":")[1]);
            hasCyclicDependencies(modCategories, parents, dependencyModid)
        }}
        // Warn about missing gradle properties
        if (!providers.gradleProperty("enable_${getCategoryName entry.key}").present && !entry.key.contains("[constraint]"))
            println("Category '${entry.key}' has no gradle properties definition. This will be assumed to be false.")
        // Add as scanned category for checking duplicates
        scannedCategories.add(getCategoryName(entry.key))
    }
}

static void hasCyclicDependencies(Map<String, List<String>> modCategories, List<String> parents, String dependency) {
    // Find category for dependency
    if (dependency.contains("#")) {
        // Get any category for name
        dependency = findCategory(modCategories, dependency);
    } else {
        // Only search for constraints for regular mod
        dependency = "[constraint]:${dependency}"
    }
    // Throw error if there is a cycle
    if (parents.contains(dependency))
        throw new RuntimeException("Cyclic dependency '${dependency}' found in tree: ${parents}");
    // Skip if such dependency is not existent
    if (!modCategories.containsKey(dependency))
        return
    // Iterate for sub-dependencies
    parents.add(dependency);
    modCategories.get(dependency).stream().forEach {subDependency -> {
        hasCyclicDependencies(modCategories, parents, subDependency)
    }}
    parents.remove(dependency)
}

Map<String, Set<String>> applySubCategories(Map<String, List<String>> modCategories) {
    Map<String, Set<String>> newModCategories = new HashMap<>()
    modCategories.forEach {category, entries ->
        newModCategories.put(category, applySubCategory(modCategories, category, new ArrayList<String>()))}
    return newModCategories
}

Set<String> applySubCategory(Map<String, List<String>> modCategories, String workingCategory, List<String> iteratedCategories) {
    // Find the working category actually exists
    workingCategory = findCategory(modCategories, workingCategory);
    // Add working category
    iteratedCategories.add(workingCategory)
    // Iterate for entries
    Set<String> filledEntries = new HashSet<>()
    modCategories.get(workingCategory).forEach {entry ->
        // If entry is non-existent, remove
        if (entry == null || entry.isEmpty())
            return
        // Add normally if it's a regular modid entry
        if (!entry.contains("#"))
            filledEntries.add(entry)
        // Apply subcategories for entry
        else filledEntries.addAll(applySubCategory(modCategories, entry, iteratedCategories))
    }
    // Remove working category: Avoids sibling branches duplicating entries in iterated categories
    iteratedCategories.remove(workingCategory)
    return filledEntries
}

static String findCategory(Map<String, List<String>> modCategories, String rawCategory) {
    rawCategory = rawCategory.replace("#", "")
    String oldName = rawCategory

    if (!rawCategory.contains(":")) {
        for (var type : List.of("optional", "required", "constraint")) {
            if (modCategories.containsKey("[${type}]:${rawCategory}".toString())) {
                rawCategory = "[${type}]:${oldName}"
                break
            }
        }
    }

    if (!oldName.contains(":") && oldName == rawCategory)
        throw new RuntimeException("[ERROR]: Category \"${rawCategory}\" does not exist in ${JsonOutput.prettyPrint(JsonOutput.toJson(modCategories))}!")

    return rawCategory;
}

static String getCategoryName(String rawCategoryName) {
    return rawCategoryName.trim().split(":")[1]
}

// Do not make this static
// Function: Has no unfulfilled requirements & atleast one option
boolean isModEnabled(List<String> listedMods, Map<String, Set<String>> modCategories, String modid) {
    // Save that mod is a dependency
    listedMods.add(modid)
    //Check if modid exists
    if (!modCategories.entrySet().stream().anyMatch {category -> {
        category.value.stream().anyMatch {mod -> mod == modid}
    }}) throw new RuntimeException("${modid} does not exist in mod_categories.json!")
    //Check requirements
    boolean allRequirementsSatisfied = modCategories.entrySet().stream()
            // Get requirements
            .filter{entry -> entry.key.contains("[required]")}
            // Remove categories that are not a requirement of mod
            .filter {entry -> entry.value.stream().anyMatch {categoryModId -> (modid == categoryModId) }}
            // Test all categories to see if they are all enabled
            .allMatch { entry -> providers.gradleProperty("enable_${getCategoryName entry.key}").getOrElse("false").toBoolean()}
    if (!allRequirementsSatisfied)
        return false
    // Check constraints
    boolean allConstraintsSatisfied = modCategories
            .getOrDefault("[constraint]:" + modid, new HashSet<String>()).stream()
            // Checks if all dependencies exist first
            .allMatch {dependency -> isModEnabled(listedMods, modCategories, dependency)}
    if (!allConstraintsSatisfied)
        return false;
    // Check options
    boolean anyOptionsSatisfied = modCategories.entrySet().stream()
            // Get options
            .filter{entry -> entry.key.contains("[optional]")}
            // Remove options that are disabled
            .filter { entry ->
                providers.gradleProperty("enable_${getCategoryName entry.key}").getOrElse("false").toBoolean()}
            // Combine all enabled options' modids
            .flatMap{entry -> entry.value.stream()}
            // Test all categories to see if any are enabled
            .anyMatch{modElement -> (modid == modElement) }
    // Show when mod is loaded
    if (anyOptionsSatisfied && providers.gradleProperty("debug_mod_list").getOrElse("false").toBoolean())
        println("Mod \"${modid}\" loaded: ${anyOptionsSatisfied}")

    return anyOptionsSatisfied
}
 */