org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1
fabric_api_version=0.92.2+1.11.8+1.20.1
mixin_version=0.12.11+mixin.0.8.5
mixin_extras_version=0.5.5
mixin_conditional=0.6.4

## Mod Selection
enable_kubejs=true

enable_libraries=true
enable_primitive_technology_1=true

## Mod Properties

mod_id=mobsiege
mod_name=Mobsiege
mod_license=MIT
mod_version=0.2
mod_group_id=com.stockieslad.mobsiege
mod_authors=StockiesLad
mod_description=Java mod containing features that this modpack uses

## Modpack Properties
modpack_version=0.1
backupRun=false
backupPack=true

# /pack/ -> [Copy] -> /runs/
staticAssetFolders=config
# /runs/ -> [Sync] -> /pack/
dynamicAssetFolders=kubejs