
[General]
	#The range of the explosion of a coal block.
	#Range: 0.0 ~ 256.0
	explosionRange = 5.0
	#Whether an exploding coal block should cause fire.
	causeFire = true
	#A list of extra configured items that can cause coal to explode
	configuredIgniters = []
	#A list of extra configured blocks that igniters can cause to explode
	configuredBlocks = ["thermal_and_space:oil_mars_sand", "thermal_and_space:oil_moon_sand", "thermal_and_space:oil_venus_sand", "thermal:oil_sand", "thermal:oil_red_sand"]

