
#Common changes
[common]
	#Lava monsters' maximum health.
	monsterHealth = 32.0
	#The amount of armor lava monsters have.
	monsterArmor = 5.0
	#The distance a lava monster will begin attacking. (maximum of 35)
	monsterRange = 17.0
	#Ticks a monster must wait after attacking before it can start winding up again.
	attackCooldown = 20
	#Number of fireballs shot with each attack.
	attackShots = 9
	#Ticks between each fireball shot in an attack.
	attackSpacing = 2
	#Ticks it takes before a monster can start an attack.
	attackWindup = 120

	#Spawning
	[common.spawning]
		#Allows you to choose which dimensions the Lava Monster spawns in. Add dimensions by their registry name/id, and separate them with commas, no spaces.
		dimensionWhitelist = "minecraft:overworld,minecraft:the_nether,good_nights_sleep:nightmare"

