//file:noinspection DependencyNotationArgument
//file:noinspection SpellCheckingInspection


import com.stockieslad.mobsiege.mod_category.ModHandler

repositories {
    mavenCentral()
    flatDir {dir 'libs'}
    flatDir {dir 'pack/mods'}

    maven { url 'https://maven.fallenbreath.me/releases' }

    maven {
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }

    maven {
        url = 'https://curse.cleanroommc.com'
        content { includeGroup 'curse.maven' }
    }

    maven {
        url = "https://maven.su5ed.dev/releases/"
    }

    maven {
        url "https://cursemaven.com"
    }

    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    annotationProcessor("org.sinytra:sponge-mixin:${mixin_version}")
    compileOnly("org.sinytra:sponge-mixin:${mixin_version}")
    //clientAdditionalRuntimeClasspath project(':mixin-bootstrap') // Do not remove me!
    implementation(jarJar "me.fallenbreath:conditional-mixin-forge:${mixin_conditional}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}"))
    implementation("org.apache.groovy:groovy:${groovy_version}")
    implementation("org.apache.groovy:groovy-json:${groovy_version}")

    compileOnly "dev.su5ed.sinytra.fabric-api:fabric-api:${fabric_api_version}"
    modCompileOnly("curse.maven:epic-mob-siege-nightmare-957414:5003615")
    modCompileOnly "net.jmb19905:carbonize:1.0.0+1.20.1"
    modCompileOnly(pack.curseforge.cb.multipart)
    modCompileOnly(pack.curseforge.no.tree.punching)
    modCompileOnly(pack.curseforge.tough.as.nails)
    modCompileOnly "buildcraft:buildcraft:7.99.24.9-1.20.1-2025-04-26-all"
    modCompileOnly(pack.curseforge.cofh.core)
    modCompileOnly(pack.curseforge.actually.subtractions)
    modCompileOnly(pack.curseforge.decorative.blocks)
    modCompileOnly("cofh.thermal.foundation:thermal_core:1.20.1-11.0.6.24")

    var modidToFile = [
            "connectormod": "org.sinytra.connector:Connector-1.0.0-beta.50+1.20.1",
            "aether_genesis": "com.aetherteam.aether_genesis:aether_genesis:1.20.1-0.0.1-forge",
            "carbonize": "net.jmb19905:carbonize:1.0.0+1.20.1",
            "buildcraftcore": "buildcraft:buildcraft:7.99.24.9-1.20.1-2025-04-26-all",
    ]

    var mods = modpack.modCategoryProvider().getModHandler() as ModHandler

    mods.addEnabledDependencies {modid -> {
        if (modidToFile.containsKey(modid)) {
            modRuntimeOnly(modidToFile[modid])
            //  if (mod == 'connectormod')
            //      modRuntimeOnly(pack.curseforge.sinytra.connector)
            //      clientAdditionalRuntimeClasspath project(':mixin-bootstrap') // Do not remove me!
        } else {
            var dep = pack.curseforge

            try {
                for (var modid_part in modid.split(/[-_|]/))
                    dep = dep."${modid_part}"
            } catch (RuntimeException exception) {
                exception.print("[ERROR]: Mod ${modid} has no dependency definition in \"dependencies.gradle#modidToFile\" map!")
                throw exception
            }

            modRuntimeOnly(dep)
        }
    }}

    configurations.configureEach {
        exclude(group: "net.minecraftforge", module: "srgutils")
    }
}