buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.electronwill.night-config:toml:3.9.0'
    }
}


import com.electronwill.nightconfig.core.file.FileConfig

import java.nio.file.Files
import java.nio.file.StandardCopyOption

tasks.register('backupPack') {
    if (providers.gradleProperty("backupPack").getOrElse("false").toBoolean()) {
        doLast {
            def timestamp = new Date().format('yyyyMMdd-HHmmss')
            def backupDir = file("${layout.buildDirectory.get()}/pack-backups/$timestamp")

            copy {
                from('pack')
                into(backupDir)
            }

            println("Backed up /pack/ to ${backupDir}")
        }
    } else doLast {
        println("Skipped '/pack/' backup.")
    }
}

tasks.register('backupRun') {
    if (providers.gradleProperty("backupRun").getOrElse("false").toBoolean()) {
        doLast {
            def timestamp = new Date().format('yyyyMMdd-HHmmss')
            def backupDir = file("${layout.buildDirectory.get()}/run-backups/$timestamp")

            copy {
                from('run')
                into(backupDir)
            }

            println("Backed up /pack/ to ${backupDir}")
        }
    } else doLast {
        println("Skipped '/run/' backup.")
    }
}

tasks.register('processStaticAssets', Copy) {
    dependsOn('backupPack')
    dependsOn('backupRun')
    into('run')

    staticAssetFolders.split(',').each { dir ->
        dir = dir.trim()
        from("pack/${dir}") {
            into(dir)
        }
    }
}

['runClient', 'runServer', 'runData'].each { name ->
    tasks.named(name) {
        dependsOn('processStaticAssets')
    }
}

tasks.register('processDynamicAssets') {
    dependsOn('backupPack')
    dependsOn('backupRun')

    doLast {
        dynamicAssetFolders.split(',').each { dir ->
            dir = dir.trim()
            sync {
                it.from("run/${dir}")
                it.into("pack/${dir}")
            }
        }
    }
}

tasks.register('updatePackToml') {
    def packFile = file(layout.projectDirectory.dir("pack/pack.toml"))
    def packToml = FileConfig.of(packFile)
    packToml.load()
    packToml.set('version', modpack_version)
    packToml.set('name', mod_name)
    packToml.save()
    println("Updated pack.toml with current values")
}

tasks.register('refreshPackwiz', Exec) {
    dependsOn('updatePackToml')
    workingDir layout.projectDirectory.dir("pack")
    commandLine 'packwiz', 'refresh'

    doLast {
        def packFile = file(layout.projectDirectory.dir("pack/pack.toml"))
        def packToml = FileConfig.of(packFile)
        packToml.load()
        packToml.set('version', modpack_version)
        packToml.set('name', mod_name)
        packToml.save()
        println("Updated pack.toml with current values")
    }
}

tasks.register('compilePackwiz') {
    dependsOn('backupPack', 'backupRun', 'refreshPackwiz', 'build')

    doLast {
        sync {
            it.from layout.projectDirectory.dir("pack")
            it.into layout.buildDirectory.dir("packwiz/compiled")
        }
        println('Added packwiz files...')
        dynamicAssetFolders.split(',').each { dir ->
            dir = dir.trim()
            copy {
                it.from"run/${dir}"
                it.into layout.buildDirectory.dir("packwiz/compiled/${dir}")
            }
        }
        println('Added dynamic asset folders...')
        def modJar = layout.buildDirectory
                .file("libs/${mod_id}-${mod_version}.jar")
                .get()
                .asFile
        def modCompilationDir = layout.buildDirectory.dir("packwiz/compiled/mods").get().asFile
        modCompilationDir.mkdirs()
        Files.copy(
                modJar.toPath(),
                modCompilationDir.toPath().resolve(modJar.name),
                StandardCopyOption.REPLACE_EXISTING
        )
        println('Added mod jar...')
    }
}

tasks.register('packwizCurseforgeExport', Exec) {
    dependsOn('compilePackwiz')
    workingDir layout.buildDirectory.dir("packwiz/compiled")
    commandLine 'packwiz', 'curseforge', 'export'
}

tasks.register('migratePackwizBuildArtifact') {
    dependsOn('packwizCurseforgeExport')
    doLast {
        def buildArtifact = file(layout.buildDirectory.file("packwiz/compiled/${mod_name}-${modpack_version}.zip"))
        def buildDir = layout.buildDirectory.dir("packwiz/artifacts").get().asFile
        buildDir.mkdirs()
        Files.move(
                buildArtifact.toPath(),
                buildDir.toPath().resolve(buildArtifact.name),
                StandardCopyOption.REPLACE_EXISTING
        )
        println("Migrated ${mod_name}-${modpack_version}.zip to artifacts..")
    }
}

tasks.register('packwizExport') {
    dependsOn('migratePackwizBuildArtifact')
}