pack-format = "packwiz:1.1.0"
author = "StockiesLad"
name = "Mobsiege"
version = "0.1"

[versions]
	minecraft = "1.20.1"
	forge = "47.4.23"

[options]
	acceptable-game-versions = ["fabric", "forge", "neoforge"]

[index]
	hash-format = "sha256"
	hash = "c9096a7d1233f5d0548cedd920e542be0c0743e9b8f0e658047e91f80fc31c71"
	file = "index.toml"
