name = "Mobsiege"
author = "StockiesLad"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e86a39ff8d8f31b18f7a97585fe897cb24233fdeaab8ee417b04c07ea2e5e61"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric", "forge", "neoforge"]
