pack-format = "packwiz:1.1.0"
author = "StockiesLad"
name = "Mobsiege"
version = "0.1"

[versions]
	minecraft = "1.20.1"
	forge = "47.4.23"

[options]
	acceptable-game-versions = ["fabric", "forge", "neoforge"]

[index]
	hash-format = "sha256"
	hash = "fe276ac095fb98a080a1577e1922b847f87805be922303650d31aa4041cf4024"
	file = "index.toml"
