// Do not delete
// Connector doesn't parse the mixin config java arguments (which MDG uses)
// This is a replacement to boot the mixin config.
// You can ignore "Completely ignored arguments: [--mixin.config, mixins.mobsiege.json]"

plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

repositories {
    mavenCentral()

    maven { url 'https://maven.fallenbreath.me/releases' }

    maven {
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }

    maven {
        url = 'https://curse.cleanroommc.com'
        content { includeGroup 'curse.maven' }
    }

    maven {
        url = "https://maven.su5ed.dev/releases/"
    }

    maven {
        url "https://cursemaven.com"
    }

    maven {
        url = 'https://maven.fabricmc.net/'
    }

    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'sponge'
        url = 'https://repo.spongepowered.org/maven'
    }
}

dependencies {
    compileOnly 'org.ow2.asm:asm:9.5'
    compileOnly 'org.ow2.asm:asm-tree:9.5'
    compileOnly 'cpw.mods:modlauncher:10.0.9'
    compileOnly 'org.spongepowered:mixin:0.8.5'
}
