recipes((event, funcs) => {
     funcs.globalPressing(content.wet_mud_brick, content.mud_ball)
     funcs.globalPressing(content.wet_aether_mud_brick, content.aether_mud_ball)
     funcs.globalPressing(content.wet_silt_brick, content.silt_ball)
     funcs.globalPressing(content.wet_holysilt_brick, content.holysilt_ball)
     funcs.globalPressing(content.wet_ash_clay_brick, content.ash_clay_ball)
     funcs.globalPressing(content.wet_clay_brick, content.clay_ball)
     funcs.globalPressing(content.wet_mortar_brick, content.mortar)
     funcs.globalPressing(content.wet_cement_brick, content.cement_compound)
})